### ISSUE TITLE
Add LEARN.md

### ISSUE THREAD

**Issue by harshiniks** [sanjay-kv/Stackoverflow-Analysis#2]
Learn repos should have a LEARN.md file to teach another student how to build your project step by step. You can explain how to build your project with text, code snippets, images, or even short (5 minute) long video lessons. As the maintainer of a Learn repo, the LEARN.md file requires you to think critically about how to explain the building of your project and how to also make it engaging. We don't expect you to be an expert teacher, but we would like you to reflect on how difficult it was to get to your level of knowledge, and then provide friendly guidance to help other students to learn.

**Comment by sanjay-kv** [comment]
This may take 2 days from the side to update as the project is intermediate level and there is a complex process in replication of the same.
