### ISSUE TITLE
Add Topics

### ISSUE THREAD

**Issue by harshiniks** [sanjay-kv/Stackoverflow-Analysis#3]
In Community Exchange, GitHub Topics will help the discoverability of your project.

I see that you already have great topics on your repository! If you happened to use any offers in the [GitHub Student Developer Pack](https://education.github.com/pack#offers) to build this project, I would recommend adding the name of the company who provided the offer to improve your discoverability.

If you did not use any additional offers and you are happy with the topics you have, feel free to close this issue. 👍

**Comment by sanjay-kv** [comment]
I have added the name of the companies in the topics section on the main branch. Let me know if you want to close this issue @harshiniks

**Comment by harshiniks** [comment]
Awesome! Do you think 'stack-overflow' topic will make sense too?

**Comment by sanjay-kv** [comment]
Yes, that's will increase the visibility of the people/students to find out the repository. I have added 'stack-overflow' & 'survey-analysis' topic.
