### ISSUE TITLE
Add issues

### ISSUE THREAD

**Issue by harshiniks** [sanjay-kv/Stackoverflow-Analysis#5]
As the maintainer of a Collaborate repo, keeping Issues up-to-date will help the student community understand what they can do to contribute. Issues should vary by the easy (update documentation) to the difficult (add a new feature). The more involved you are, the more opportunities there are to collaborate.

Recommendations:

Add issues of varying difficulty to the repo often.
Generate issues even if you plan on solving them, so the repository appears as active.
Contribute/commit often to the repo so it does not go stale.
In order to submit your project into CX you will need at least one issue, but we recommend more so other students have an idea on where to start.

**Comment by sanjay-kv** [comment]
You can close this Issue, I have added a couple of high and low priority issues which required some hands-on documentation and visualization within the project. 

#9 #10 #11 #12 #13
